image: node:8
# Build - Build necessary JS files
# Test - Run tests
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
    - build
    - deploy
    
cache:
  paths:
  - ./server/node_modules/
  
# Job: Build
build:
  stage: build
  script:
    - cd ./server
    - npm install
    - cd ../client
    - npm install

deploy:
    stage: deploy
    script:
        - cd ./server
        - npm run start
        - cd ../client
        - npm run start
