# Build - Build necessary JS files
# Test - Run tests
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
  - build
  
# Job: Build
build:
  stage: build
  script:
    - cd ./server
    - yarn install
