image: node:8
# Build - Build necessary JS files
# Test - Run tests
# Deploy - Deploy application to S3/ElasticBeanstalk
stages:
    - build
    - deploy
  
# Job: Build
build:
  stage: build
  script:
    - cd ./server
    - npm install

deploy:
    - cd ../client